name: 'AWS Account ID read'
description: 'Reads AWS Account ID from Watchman API'
inputs:
      workload_name:
        description: 'Name of the workload'
        required: true
      ou_name:
        description: 'OU name'
        required: true

outputs:
  accountId:
    description: "AWS Account ID"
    value: ${{ steps.account_id.outputs.accountId }}

runs:
  using: "composite"
  steps:    
    - name: Get account Id
      id: account_id
      run: ${{ github.action_path }}/scripts/GetAWSAccountId.ps1
      shell: pwsh
      env:
        workload_name: ${{ inputs.workload_name }}
        ou_name: ${{ inputs.ou_name }}
